DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;

CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY, AUTHORNAME VARCHAR(255) UNIQUE);
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY, GENRENAME VARCHAR(255) UNIQUE);
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), AUTHOR_ID BIGINT, GENRE_ID BIGINT,CONSTRAINT UC_Book UNIQUE (NAME, AUTHOR_ID, GENRE_ID));


ALTER TABLE BOOKS
    ADD CONSTRAINT fk_author FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(id);
ALTER TABLE BOOKS
    ADD CONSTRAINT fk_genre FOREIGN KEY(GENRE_ID) REFERENCES GENRES(id);
